# Permalinks
permalink:           pretty

# Setup
title:               He Dejing
tagline:             Zhejiang University, Computer Science and Technology
url:                 http://hedejing.github.io
paginate:            1
baseurl:             "http://hedejing.github.io"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              He Dejing
  url:               http://hedejing.github.io
  email:             hedejing@outlook.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/hedejing/hedejing.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
