# general configuration
url: https://tomstream.github.io
baseurl: ''
navi: ''
# compass configuration
configs:
  # an avatar or logo (optional)
  logo: "/images/miao.jpeg"
  # author will appear under the avatar (optional)
  title: "Zongtao Liu"
  # tagline will appear under the title (optional)
  tagline: "刘宗涛  tomstream@zju.edu.cn <br> Where there's hope, there's a trial."
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# exclude
exclude: ["CNAME", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
